### ISSUE TITLE
Come join us!

### ISSUE THREAD

**Issue by samccone** [sadcitizen/marionettejs.ru#34]
hey @instanceofpro just found this repo (and site), amazing work! We would love to have you come join us over on the main www repo and we can chat about how we can get this integrated!!!!

again amazing amazing work!!!

**Comment by sadcitizen** [comment]
Thank you appreciated my work, but it isn't finished yet. Some sections need to edit.

**Comment by samccone** [comment]
ah no worries, any support is better than none. :clap: keep up the amazing work!
