### ISSUE TITLE
404 instanceof.pro/marionettejs.ru

### ISSUE THREAD

**Issue by MitoZ** [sadcitizen/marionettejs.ru#51]
Хотелось бы узнать про судьбу перевода, а то вот уже как с неделю-другую страничка instanceof.pro/marionettejs.ru 404 Т_Т

**Comment by sadcitizen** [comment]
Он никуда не делся :) Я поменял логин на гитхабе. Потому поменялся урл. Гитхаб почему-то не делает редирект. Постараюсь в ближайшее время причесать перевод и выложить на домен marionettejs.ru. Спасибо за беспокойство. Сейчас перевод доступен по адресу  http://sadcitizen.github.io/marionettejs.ru/

**Comment by sadcitizen** [comment]
Перевод доступен на http://marionettejs.ru
